name: money_plan
description: "household toyproject"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  path_provider: ^2.0.14
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_colorpicker: ^1.0.3
  collection: ^1.18.0
  fl_chart: ^0.71.0
  syncfusion_flutter_datepicker: ^29.1.39
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.10+1
  table_calendar: ^3.1.3
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  hive_generator: ^2.0.1
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_foreground: "assets/icons/ic_fg.png"
  adaptive_icon_background: "assets/icons/ic_bg.png"
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/AIA.png
    - assets/img/AIG.png
    - assets/img/AXA.png
    - assets/img/BC_CARD.png
    - assets/img/BNK.png
    - assets/img/BNP.png
    - assets/img/BOA.png
    - assets/img/BOOGUG.png
    - assets/img/CHUBB.png
    - assets/img/CIGNA.png
    - assets/img/CITI.png
    - assets/img/DAESIN.png
    - assets/img/DB.png
    - assets/img/DGB.png
    - assets/img/DOICHI.png
    - assets/img/GWANGJU.png
    - assets/img/HANA.png
    - assets/img/HANHWA.png
    - assets/img/HEONGUK.png
    - assets/img/HSBC.png
    - assets/img/HYUNDAI.png
    - assets/img/IBK.png
    - assets/img/JPMORGAN.png
    - assets/img/KAKAO.png
    - assets/img/KB.png
    - assets/img/KBANK.png
    - assets/img/KDB.png
    - assets/img/KIUM.png
    - assets/img/KTB.png
    - assets/img/KYOBO.png
    - assets/img/KYOBO_PLANET.png
    - assets/img/LOTTE.png
    - assets/img/MERITZ.png
    - assets/img/MG.png
    - assets/img/MIRAE.png
    - assets/img/NONGHYB.png
    - assets/img/RGA.png
    - assets/img/SAMSUNG.png
    - assets/img/SANLIM.png
    - assets/img/SBI.png
    - assets/img/SC.png
    - assets/img/Sh.png
    - assets/img/SINHAN.png
    - assets/img/SINYEONG.png
    - assets/img/SK.png
    - assets/img/TOSS.png
    - assets/img/UCHEGUK.png
    - assets/img/WOORI.png
    - assets/img/cash.png
